server:
  port: 8081

tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8002

spring:
  profiles:
    active: debug
---
spring:
  profiles: debug
  datasource:
    username: ENC(dS27bnAu1ent59/kxiNPLQ==)
    password: ENC(8zIz7elyRxJZqTUCL2NXhoQUEelb+039)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(js3nRPAN98pfzxyLGb4ZVk+2DCFhQxxJbALCm2LTUCn88NJqcldMrkgNnc+n0Xnut707TJG3FGV+gvPAf7vZ8XjHqiozMGz9NWePBSWFzarAmVzeXJm0JB+8MCSDBEvAqatLo8yqp0AgtSyf5dujQfqQ+OE19yZs2gVNetfBgQQVuJIc//v0/S0S7aEa7nfEEf9Bj2s37FF/sdmZnK6GR+sXTgT7VHFVbwyVuJUpuGhs9igxd9HoQkbkLFWgOCKOAUbIbjsFduyKgTaHtwn6KXBBSHIrRvL+26tZOAWKr70kLXAUf/Opf1p8SkHi7bneDz+LXgo7CGr2la+JR3Z/ZBq12g8CsfOwB9DWch9nw0EXcKUayxsm7yi6k+X+IGAYR3MLWlkoBWXXGFLS7FbIblBZZTnmQkdc8zhi/kLGCZBM10FGSSzokXE+QSeOSdQ4VWF1DSIswPJISLS5E+xgISfKLuu8+qC9/RZ6MgIlj8TzR7ZVqMCzWqrkLprJ486I)
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring: 
  profiles: release
  datasource:
    username: ENC(JjIQfD5FgIZMhcGyMR+oRQ==)
    password: ENC(Qt+sX9+pG90vsMqGoLyvG3I53rssKw/1)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(NzSjIujFVTh1fVcqtqcgMnUvs4Vx42JrX75//3DAXV9VFeiwamJK6bndyGmaaZL72xO45IlSp+VR+BHM5luf4M/h7i2JepCayNCwWEqI3btu7jYbWUa73pA7Nv6fuPQ3RxE4/TObedcRSZk6pY2kWJtPlTXl6llgqVsPZeD0WPG/UYj9193G05lkKUQT4VB5uAWOgyXkkXnLImWNFCGE/5z3BxpRu+GoNVhcBx7Ew4lj0iVVMskt3C2D1fkCH2l6n8TzhHGG58xuE0cEwmhUI2yzNC2zd9fD09qEboxt6m+gF5gi4ijFds6ynMEnkfKHfj6jqie894BnKyzqu9pErP3k95LzG95OzJJBj9IGR2g9GMuvaRdZ5DDXa6tg/sI4OqovHqYJDgnXY+PBh7d6fYcfzjfFxR3uhm1fwBoNpniVEueXRVm87zbQJuxbg4xz+CmxvK+eoU5Pr4CxjpCUTh8piBaO4aYp+33/o8KXaDvthnmXqfapd9RQ2F79uSdq)

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
      main:
        allow-bean-definition-overriding: true
    database: default
  thymeleaf:
        prefix : classpath:/templates/
        suffix : .html
        cache : false
        check-template-location: true
        order : 0
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"
    authorization:
      token-key-access: isAuthenticated()
kafka:
   bootstrapAddress: localhost:9092
message:
   topic: mytopic
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

