server:
  port: 8081

tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8002

spring:
  profiles:
    active: debug
---
spring:
  profiles: debug
  datasource:
    username: ENC(dS27bnAu1ent59/kxiNPLQ==)
    password: ENC(8zIz7elyRxJZqTUCL2NXhoQUEelb+039)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(AHSYchZMI+OYgSbNqVDL/4OBWDIDpqlDlNJj0AEsfqkR9IjNXj9MEWYCoUvPTaPcA0eKPOeaj+vuKguFPVVvLwI+uoDJSwK59aoR0+r6Eik=)
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring: 
  profiles: release
  datasource:
    username: ENC(JjIQfD5FgIZMhcGyMR+oRQ==)
    password: ENC(Qt+sX9+pG90vsMqGoLyvG3I53rssKw/1)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(+p+4kvjeWyMSm8kjIEgAbeqnpPYNfUT9DcnInu6csaAzkBeziw2Glr7psOHvrV6uqCEH86bnguxOdt8lngLXTA==)

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
      main:
        allow-bean-definition-overriding: true
    database: default
  thymeleaf:
        prefix : classpath:/templates/
        suffix : .html
        cache : false
        check-template-location: true
        order : 0
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"
    authorization:
      token-key-access: isAuthenticated()
kafka:
   bootstrapAddress: localhost:9092
message:
   topic: mytopic
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

